name: first_work_flow

env:
  msg: "Hey! I Am Ashu"
  age: 21

on:
  push:
    branches: [ "Cool" ]
    
  workflow_dispatch:



jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo $msg

  second_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo $age

  # third_job:
  #   runs-on: [self-hosted, linux]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run a one-line script
  #       run: echo third-job
