name: first_work_flow

env:
  msg: "Hey! I Am Ashu"
  age: 21

on:
  push:
    branches: [ "Cool" ]
    
  workflow_dispatch:



jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo $msg

  second_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo $age

  third_job:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: My Pyhton
        run: python my_script.py

