name: first_work_flow
on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

env:
  var = 80

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo first-job

  second_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo $var

  # third_job:
  #   runs-on: [self-hosted, linux]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run a one-line script
  #       run: echo third-job
